wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1668161499.884118
    t:
      1:
      - 1
      - 5
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 49
      - 51
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.6
      5: 0.13.5
      8:
      - 5
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 1000
learning_rate:
  desc: null
  value: 0.01
model_name:
  desc: null
  value: glove-wiki-gigaword-100
